### ISSUE TITLE
[BUG] Slack avatar doesn't load properly

### ISSUE THREAD

**Issue by ultimatehecker** [polypixeldev/FinalFinder#15]
### Description

Whenever you enter the upcoming exams home menu, the listed people's avatar icon doesn't show

### Reproduction

1. Register yourself for an exam
2.  Go back to your dashboard
3. Click on the exam

### Expected behavior

It should display the users slack avatar picture

### Additional context

![image](https://user-images.githubusercontent.com/86735991/233814088-2d91a964-db7e-4b47-ac3d-bd25fea88876.png)

**Comment by polypixeldev** [comment]
I see the issue, your pfp was a gravatar and it wasn't configured to allow for gravatar images. Check if it's fixed now @ultimatehecker
