### ISSUE TITLE
[FR] Add a proper image to the tab

### ISSUE THREAD

**Issue by ultimatehecker** [polypixeldev/FinalFinder#16]
### Problem

Whenever you visit the website, the icon on the tab your on is the standard next-vercel template icon

### Solution

It would be nice to have a proper icon

### Alternatives

It has to be edited in `src/pages/_app.tsx`

### Additional context

![image](https://user-images.githubusercontent.com/86735991/233814154-0a26f2eb-b7e9-4809-8888-5196dddeb268.png)

**Comment by polypixeldev** [comment]
Yeah this would be nice, although not really a priority for me right now. Do you want to work on this @ultimatehecker ?

**Comment by ultimatehecker** [comment]
> Yeah this would be nice, although not really a priority for me right now. Do you want to work on this @ultimatehecker ?

I mean I could work on it, it's not that hard I would just have to make an image or find a good on on the internet and make it an ico
