### ISSUE TITLE
[BUG] Cannot create an study session for exam

### ISSUE THREAD

**Issue by ultimatehecker** [polypixeldev/FinalFinder#17]
### Description

Whenever I try to create a study session for an exam, I can't create one even if a date and exam name is specified

### Reproduction

1. Go to the home dashboard
2. Add a new study session
3. Watch the create button not actually be a button

### Expected behavior

You should be able to properly create a study session

### Additional context

An exam date and name was provided:
![image](https://user-images.githubusercontent.com/86735991/233814392-cfba4995-6726-4e37-bafd-cebf445716d2.png)

**Comment by polypixeldev** [comment]
You only specified the date, not the time. Do you think that it should be made clearer?

**Comment by ultimatehecker** [comment]
> You only specified the date, not the time. Do you think that it should be made clearer?

You cannot specify a time, I tried to and thought it was bugged @polypixeldev

**Comment by polypixeldev** [comment]
The date time picker is handled by the browser - I think in Firefox you have to press tab to enter in the time

**Comment by ultimatehecker** [comment]
Definitionally has to be clear, i dont know how though beacuse that seems like a browser issue
